version: '3.7'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    env_file: 
      - .env
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    command: python3 musicsync/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on: 
      - db
      - redis
  frontend:
    build: ./frontend/
    command: npm start
    volumes: 
      - ./frontend:/app/frontend/
      - /app/frontend/musicsync/node_modules
    ports:
      - "3000:3000"
    environment: 
      - NODE_ENV = DEV
    depends_on: 
      - backend
    


volumes:
  db-data:
